import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { poppins } from "./fonts";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full relative">
      <body className={`${poppins.className} antialiased`}>
        <Navbar />
        <div className="max-w-7xl mx-auto px-7 mt-28">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
